package com.sky.config;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.Optional;
import org.junit.Before;
import org.junit.Test;

public class PersistentStateTest {

    private PersistentState persistentState;

    @Before
    public void setUp() throws Exception {
        persistentState = new PersistentState();

        persistentState.refreshCookiesCache("{\n"
                + "  \"yapi.kaikeba.com\": [\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"expirationDate\": 1639716133,\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"Hm_lvt_156e88c022bf41570bf96e74d090ced7\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"1606130488,1607944020,1608180133\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"corgi-token-test-data\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"f882b783-3e84-4bfe-bb56-db8ce85950a8\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"expirationDate\": 1616918560,\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"UM_distinctid\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"174ce95d631153-0dee1fa9c473d1-31697304-13c680-174ce95d6326b0\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"corgi-token-prod-data\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"38e2eeed-4584-4907-80ac-8ecc3cc805b4\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"expirationDate\": 1916183537,\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"grwng_uid\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"fa0003c2-8f70-4322-8258-71c840f536da\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"kd_5d6526d7-3c9f-460b-b6cf-ba75397ce1ac_view_log_id\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"VTVJPlTS0TFtsmT3Dnx\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"kd_5d6526d7-3c9f-460b-b6cf-ba75397ce1ac_log_id\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"U176VMs6iWono23XVFQ%3A224f9855-b3ea-4e91-8cb5-701fba51c5a4%3Afdecbfef-4320-4fa9-a9ad-ec951d631e61\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"kd_5d6526d7-3c9f-460b-b6cf-ba75397ce1ac_kuickDeal_leaveTime\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"1608180137537\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"Hm_lpvt_156e88c022bf41570bf96e74d090ced7\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"1608180133\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"expirationDate\": 1923541030,\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"gr_user_id\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"bda10e66-75b2-41bd-b216-a13e1af902f1\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \"yapi.kaikeba.com\",\n"
                + "        \"expirationDate\": 1608785350.128361,\n"
                + "        \"hostOnly\": true,\n"
                + "        \"httpOnly\": true,\n"
                + "        \"name\": \"_yapi_token\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjYwOCwiaWF0IjoxNjA4MTgwNTUwLCJleHAiOjE2MDg3ODUzNTB9.SUtq2oWYi2i48dIb0UCFYZb06OWQoLLk5da8ht7tOG4\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"expirationDate\": 1668240986,\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"_ga\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"GA1.2.370407192.1605168675\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \"yapi.kaikeba.com\",\n"
                + "        \"expirationDate\": 1608785350.128615,\n"
                + "        \"hostOnly\": true,\n"
                + "        \"httpOnly\": true,\n"
                + "        \"name\": \"_yapi_uid\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"608\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"kd_5d6526d7-3c9f-460b-b6cf-ba75397ce1ac_kuickDeal_pageIndex\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": true,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"0\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"domain\": \".kaikeba.com\",\n"
                + "        \"expirationDate\": 1916183537,\n"
                + "        \"hostOnly\": false,\n"
                + "        \"httpOnly\": false,\n"
                + "        \"name\": \"kd_user_id\",\n"
                + "        \"path\": \"/\",\n"
                + "        \"sameSite\": \"unspecified\",\n"
                + "        \"secure\": false,\n"
                + "        \"session\": false,\n"
                + "        \"storeId\": null,\n"
                + "        \"value\": \"a6c93472-3c40-4580-9c21-3e1f55bc9495\"\n"
                + "    }\n"
                + "]\n"
                + "}");

        persistentState.refreshConfigCache("[\n"
                + "  {\n"
                + "    \"moduleName\": \"lbgc-pay-center\",\n"
                + "    \"projectToken\": \"token-for-test\",\n"
                + "    \"projectId\": 1758,\n"
                + "    \"yApiUrl\": \"http://yapi.kaikeba.com/\",\n"
                + "    \"menu\": \"\",\n"
                + "    \"projectType\": \"api\",\n"
                + "    \"reqBodyIsJsonSchema\": true,\n"
                + "    \"resBodyIsJsonSchema\": true\n"
                + "  },\n"
                + "  {\n"
                + "    \"moduleName\": \"lbgc-app-service\",\n"
                + "    \"projectId\": 1942,\n"
                + "    \"yApiUrl\": \"http://yapi.kaikeba.com/\",\n"
                + "    \"menu\": \"Service端-师资时间管理\",\n"
                + "    \"projectType\": \"api\",\n"
                + "    \"reqBodyIsJsonSchema\": true,\n"
                + "    \"resBodyIsJsonSchema\": true\n"
                + "  },\n"
                + "  {\n"
                + "    \"moduleName\": \"baidu-module\",\n"
                + "    \"projectToken\": \"token-for-test\",\n"
                + "    \"projectId\": 1942,\n"
                + "    \"yApiUrl\": \"http://www.baidu.com/\",\n"
                + "    \"menu\": \"Service端-师资时间管理\",\n"
                + "    \"projectType\": \"api\",\n"
                + "    \"reqBodyIsJsonSchema\": true,\n"
                + "    \"resBodyIsJsonSchema\": true\n"
                + "  }\n"
                + "]\n");
    }

    @Test
    public void refreshConfigCache() {
        assertThat(PersistentState.COOKIES_CACHE.containsKey("yapi.kaikeba.com")).isTrue();
        Optional<ConfigEntity> config = persistentState.getConfig("lbgc-pay-center");
        assertThat(config.isPresent()).isTrue();
        assertThat(config.get().getCookies()).isNotEmpty();
        assertThat(config.get().getProjectToken()).isNull();
    }

    @Test
    public void refreshConfigWithout_cookies() {
        assertThat(PersistentState.COOKIES_CACHE.containsKey("www.baidu.com")).isFalse();
        assertThat(PersistentState.MODULE_NAME_TO_HOST.get("www.baidu.com")).isNull();
        Optional<ConfigEntity> config = persistentState.getConfig("baidu-module");
        assertThat(config.isPresent()).isTrue();
        assertThat(config.get().getCookies()).isNullOrEmpty();
    }

}